version: "3.7"
services:
  jammy:
    build:
      context: .
      dockerfile: jammy.dockerfile
    image: incebellipipo/dockerfile:jammy
  bookworm:
    build:
      context: .
      dockerfile: bookworm.dockerfile
    image: incebellipipo/dockerfile:bookworm
