version: "3.7"
services:
  jammy:
    build:
      context: .
      dockerfile: ubuntu/jammy.dockerfile
    image: incebellipipo/dockerfile:jammy
  focal:
    build:
      context: .
      dockerfile: ubuntu/focal.dockerfile
    image: incebellipipo/dockerfile:focal
  bookworm:
    build:
      context: .
      dockerfile: debian/bookworm.dockerfile
    image: incebellipipo/dockerfile:bookworm
  humble:
    build:
      context: .
      dockerfile: ros/humble.dockerfile
    image: incebellipipo/dockerfile:humble
  noetic:
    build:
      context: .
      dockerfile: ros/noetic.dockerfile
    image: incebellipipo/dockerfile:noetic

