name: Docker Hub

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        image:
          - flavor: debian
            distro: bookworm
          - flavor: debian
            distro: bullseye
          - flavor: debian
            distro: buster

          - flavor: ubuntu
            distro: noble
          - flavor: ubuntu
            distro: jammy
          - flavor: ubuntu
            distro: focal
          - flavor: ubuntu
            distro: bionic
          - flavor: ubuntu
            distro: xenial

          - flavor: ros
            distro: humble
          - flavor: ros
            distro: noetic
          - flavor: ros
            distro: rolling
          - flavor: ros
            distro: jazzy

          - flavor: ruby
            distro: github-pages

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.flavor }}/base.dockerfile
          build-args: |
            DISTRO=${{ matrix.image.distro }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: incebellipipo/devcontainer:${{ matrix.image.distro }}
